services: 
  grafana: 
    image: grafana/grafana:latest
    ports: 
      - 3001:3000
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
    volumes: 
      - grafana-data:/var/lib/grafana
  
  influxdb: 
    image: influxdb:1.8
    ports: 
      - 8086:8086
    environment: 
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ADMIN_ENABLED=true
  
  k6:
    image: grafana/k6:latest
    ports: 
      - 8081:8081
    volumes: 
      - ./k6:/scripts
    entrypoint: ["k6", "run", "/scripts/test.js", "--out", "influxdb=http://influxdb:8086/grafana"]
  

volumes: 
  grafana-data: 